name: docker

on:
  workflow_dispatch:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: verificarlo
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
      - name: Test
        run: |
          docker run --rm verificarlo -c "make -C /build/verificarlo installcheck"